CREATE TABLE IF NOT EXISTS `wp_scene_qrcode` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
`token`  varchar(255) NULL  COMMENT '公众号Token',
`scene_name`  varchar(255) NULL  COMMENT '场景名称',
`keyword`  varchar(255) NULL  COMMENT '关联关键词',
`scene_type`  char(10) NULL  DEFAULT 0 COMMENT '二维码类型',
`scene_id`  int(32) NULL  COMMENT '场景值ID',
`scene_str`  varchar(255) NULL  COMMENT '场景值字符串',
`expire`  int(10) NULL  COMMENT '过期时间',
`ticket`  varchar(255) NULL  COMMENT '二维码Ticket',
`url`  varchar(255) NULL  COMMENT '二维码图片解析后的地址',
`ctime`  int(10) NULL  COMMENT '二维码创建时间',
`short_url`  varchar(255) NULL  COMMENT '二维码短地址',
PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci CHECKSUM=0 ROW_FORMAT=DYNAMIC DELAY_KEY_WRITE=0;
INSERT INTO `wp_model` (`name`,`title`,`extend`,`relation`,`need_pk`,`field_sort`,`field_group`,`attribute_list`,`template_list`,`template_add`,`template_edit`,`list_grid`,`list_row`,`search_key`,`search_list`,`create_time`,`update_time`,`status`,`engine_type`) VALUES ('scene_qrcode','场景二维码','0','','1','["scene_name","keyword","scene_type","scene_str","expire"]','1:基础','','','','','scene_name:场景名称\r\nkeyword:关联关键词\r\nscene_type:类型\r\nid|getSceneIdOrStr:场景值ID/字符串\r\nshort_url:二维码\r\nexpire:过期时间\r\nid|getScanTimes:扫描次数\r\nid|getScanPersons:扫描人数\r\nctime|time_format:创建时间\r\nid|getExpiretime:到期时间\r\nid:操作:[EDIT]&id=[id]|编辑,[DELETE]&id=[id]|删除,viewScan&id=[id]|查看扫描统计','10','scene_name','','1448517943','1448544430','1','MyISAM');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('token','公众号Token','varchar(255) NULL','string','','','0','','0','0','1','1448517984','1448517984','','3','','regex','get_token','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('scene_name','场景名称','varchar(255) NULL','string','','','1','','0','1','1','1448518657','1448518006','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('keyword','关联关键词','varchar(255) NULL','string','','','1','','0','0','1','1448518039','1448518039','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('scene_type','二维码类型','char(10) NULL','radio','0','','1','0:临时二维码\r\n1:永久二维码','0','0','1','1448518150','1448518150','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('scene_id','场景值ID','int(32) NULL','num','','','0','','0','0','1','1448518272','1448518252','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('scene_str','场景值字符串','varchar(255) NULL','string','','临时二维码不用填。永久二维码填写字符串或汉字，也可以不填。','1','','0','0','1','1448518467','1448518467','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('expire','过期时间','int(10) NULL','num','','以秒为单位， 最大不超过604800（即7天）。 只对临时二维码有效，永久二维码不用填。','1','','0','0','1','1448526699','1448518643','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('ticket','二维码Ticket','varchar(255) NULL','string','','','0','','0','0','1','1448519266','1448519266','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('url','二维码图片解析后的地址','varchar(255) NULL','string','','','0','','0','0','1','1448519304','1448519304','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('ctime','二维码创建时间','int(10) NULL','datetime','','','0','','0','0','1','1448519406','1448519406','','3','','regex','time','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('short_url','二维码短地址','varchar(255) NULL','string','','','0','','0','0','1','1448526642','1448524998','','3','','regex','','3','function');
UPDATE `wp_attribute` SET model_id= (SELECT MAX(id) FROM `wp_model`) WHERE model_id=0;

CREATE TABLE IF NOT EXISTS `wp_scene_qrcode_statistics` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
`token`  varchar(255) NULL  COMMENT '公众号Token',
`openid`  varchar(255) NULL  COMMENT '扫码者openid',
`scene_name`  varchar(255) NULL  COMMENT '场景名称',
`keyword`  varchar(255) NULL  COMMENT '关联关键词',
`scene_id`  varchar(255) NULL  COMMENT '场景ID/场景字符串',
`scan_type`  varchar(255) NULL  COMMENT '扫描类型',
`ctime`  int(10) NULL  COMMENT '扫描时间',
`qrcode_id`  int(10) NULL  COMMENT '二维码ID',
PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci CHECKSUM=0 ROW_FORMAT=DYNAMIC DELAY_KEY_WRITE=0;
INSERT INTO `wp_model` (`name`,`title`,`extend`,`relation`,`need_pk`,`field_sort`,`field_group`,`attribute_list`,`template_list`,`template_add`,`template_edit`,`list_grid`,`list_row`,`search_key`,`search_list`,`create_time`,`update_time`,`status`,`engine_type`) VALUES ('scene_qrcode_statistics','场景二维码扫描统计','0','','1','["scene_name","keyword","scene_id","scan_type","ctime"]','1:基础','','','','','scene_name:场景名称\r\nkeyword:关联关键词\r\nopenid|getFollowNickname:扫码者昵称\r\nopenid|getFollowHeadimg:扫码者头像\r\nscan_type|getScanType:扫码类型\r\nctime|time_format:扫码时间','10','scene_name','','1448529386','1448530035','1','MyISAM');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('token','公众号Token','varchar(255) NULL','string','','','0','','0','0','1','1448529447','1448529447','','3','','regex','get_token','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('openid','扫码者openid','varchar(255) NULL','string','','','0','','0','0','1','1448529507','1448529507','','3','','regex','get_openid','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('scene_name','场景名称','varchar(255) NULL','string','','','1','','0','0','1','1448529541','1448529541','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('keyword','关联关键词','varchar(255) NULL','string','','','1','','0','0','1','1448529562','1448529562','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('scene_id','场景ID/场景字符串','varchar(255) NULL','string','','','1','','0','0','1','1448529722','1448529722','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('scan_type','扫描类型','varchar(255) NULL','string','','','1','','0','0','1','1448529758','1448529758','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('ctime','扫描时间','int(10) NULL','datetime','','','1','','0','0','1','1448529808','1448529808','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('qrcode_id','二维码ID','int(10) NULL','num','','','0','','0','0','1','1448534367','1448533103','','3','','regex','','3','function');
UPDATE `wp_attribute` SET model_id= (SELECT MAX(id) FROM `wp_model`) WHERE model_id=0;